/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/core/AppBar.vue')['default']
    CoreInfo: typeof import('./src/components/core/CoreInfo.vue')['default']
    Footer: typeof import('./src/components/core/Footer.vue')['default']
    MainInfo: typeof import('./src/components/MainInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Summary: typeof import('./src/components/Summary.vue')['default']
  }
}
