/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./src/components/MainInfo/tabs/AboutMe.vue')['default']
    AppBar: typeof import('./src/components/core/AppBar.vue')['default']
    CoreInfo: typeof import('./src/components/core/CoreInfo.vue')['default']
    Footer: typeof import('./src/components/core/Footer.vue')['default']
    HtmlContent: typeof import('./src/components/utils/HtmlContent.vue')['default']
    Jobs: typeof import('./src/components/MainInfo/tabs/Jobs.vue')['default']
    MainInfo: typeof import('./src/components/MainInfo/index.vue')['default']
    Portfolio: typeof import('./src/components/MainInfo/tabs/Portfolio.vue')['default']
    Projects: typeof import('./src/components/MainInfo/tabs/Projects.vue')['default']
    Resume: typeof import('./src/components/MainInfo/tabs/Resume.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteInfo: typeof import('./src/components/MainInfo/tabs/SiteInfo.vue')['default']
    Summary: typeof import('./src/components/Summary.vue')['default']
  }
}
